language: generic
before_install: true
install: true
before_deploy:
  - ssh-keyscan -H $DEPLOY_HOST_DEV $DEPLOY_HOST_STAGE 2>&1 | tee -a $HOME/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_e422520171bf_key -iv $encrypted_e422520171bf_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
script: bash visual-test.sh
- provider: script
  skip_cleanup: true
  script: ssh $DEPLOY_USER_DEV@$DEPLOY_HOST_DEV "/home/root/redeploy.sh"
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: ssh $DEPLOY_USER_STAGE@$DEPLOY_HOST_STAGE "/home/redeploy.sh"
  on:
    branch: master